# Generated by Django 5.2.2 on 2025-06-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_id", models.CharField(blank=True, max_length=20, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("guest", "訪客"),
                            ("user", "一般使用者"),
                            ("admin", "管理者"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "work_area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("north", "雙北桃竹苗"),
                            ("central", "中彰投"),
                            ("south", "雲嘉南"),
                            ("kaoping", "高高屏"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=20, null=True)),
                ("district", models.CharField(blank=True, max_length=20, null=True)),
                ("village", models.CharField(blank=True, max_length=20, null=True)),
                ("neighbor", models.CharField(blank=True, max_length=10, null=True)),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                ("section", models.CharField(blank=True, max_length=10, null=True)),
                ("lane", models.CharField(blank=True, max_length=10, null=True)),
                ("alley", models.CharField(blank=True, max_length=10, null=True)),
                ("number", models.CharField(blank=True, max_length=10, null=True)),
                ("floor", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "identity_type",
                    models.CharField(
                        blank=True,
                        choices=[("public", "公"), ("private", "私")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
